name: qizme
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  pinput: ^6.0.2
  rename_app: ^1.6.5
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans-Regular.ttf

    - family: YoungSerif
      fonts:
        - asset: assets/fonts/YoungSerif-Regular.ttf
